server:
  port: 8080

spring:
  application:
    name: APIGATEWAY-MS
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Automatic routing based on Eureka service ID
          lower-case-service-id: true
      routes: # Manual routing
        - id: user_route
          uri: lb://USER-MS
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: account_route
          uri: lb://ACCOUNTMNG-MS
          predicates:
            - Path=/account-service/**
          filters:
            - RewritePath=/account-service/(?<segment>.*), /$\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
